/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { proofsCreate } from "../funcs/proofs-create.js";
import { proofsVerify } from "../funcs/proofs-verify.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Proofs extends ClientSDK {
  /**
   * Prove (sign + register) AI output
   */
  async create(
    request: models.ProveInput,
    options?: RequestOptions,
  ): Promise<models.ProofResult> {
    return unwrapAsync(proofsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Verify proof by id or hash
   */
  async verify(
    request: models.VerifyRequestUnion,
    options?: RequestOptions,
  ): Promise<operations.PostVerifyResponse> {
    return unwrapAsync(proofsVerify(
      this,
      request,
      options,
    ));
  }
}
