/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Proofs } from "./proofs.js";
import { Usage } from "./usage.js";

export class Vaibot extends ClientSDK {
  private _proofs?: Proofs;
  get proofs(): Proofs {
    return (this._proofs ??= new Proofs(this._options));
  }

  private _usage?: Usage;
  get usage(): Usage {
    return (this._usage ??= new Usage(this._options));
  }
}
