/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usageGet } from "../funcs/usage-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Usage extends ClientSDK {
  /**
   * Usage and quota
   */
  async get(
    options?: RequestOptions,
  ): Promise<models.UsageResult> {
    return unwrapAsync(usageGet(
      this,
      options,
    ));
  }
}
