/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @vaibot/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx proofsCreate.example.ts
 */

import { Vaibot } from "@vaibot/sdk";

const vaibot = new Vaibot({
  bearerAuth: process.env["VAIBOT_BEARER_AUTH"] ?? "",
});

async function main() {
  const result = await vaibot.proofs.create({
    content: "<value>",
  });

  console.log(result);
}

main().catch(console.error);
