workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Vaibot SDK API:
        inputs:
            - location: ../../openapi.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/campbell-labs-llc/vaibot/vaibot-sdk-api
targets:
    vaibot:
        target: typescript
        source: Vaibot SDK API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/campbell-labs-llc/vaibot/vaibot-sdk-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
