/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9b2d8328535a
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * OK
 */
export type PostVerifyResponse =
  | models.VerifyResultVerified
  | models.VerifyResultNotVerified;

/** @internal */
export const PostVerifyResponse$inboundSchema: z.ZodMiniType<
  PostVerifyResponse,
  unknown
> = smartUnion([
  models.VerifyResultVerified$inboundSchema,
  models.VerifyResultNotVerified$inboundSchema,
]);

export function postVerifyResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostVerifyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostVerifyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostVerifyResponse' from JSON`,
  );
}
