/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const Encoding = {
  Utf8: "utf-8",
  Base64: "base64",
} as const;
export type Encoding = ClosedEnum<typeof Encoding>;

export type ProveInput = {
  content: string;
  /**
   * MIME type
   */
  contentType?: string | undefined;
  encoding?: Encoding | undefined;
  model?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  idempotencyKey?: string | undefined;
};

/** @internal */
export const Encoding$outboundSchema: z.ZodMiniEnum<typeof Encoding> = z.enum(
  Encoding,
);

/** @internal */
export type ProveInput$Outbound = {
  content: string;
  contentType?: string | undefined;
  encoding: string;
  model?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  idempotencyKey?: string | undefined;
};

/** @internal */
export const ProveInput$outboundSchema: z.ZodMiniType<
  ProveInput$Outbound,
  ProveInput
> = z.object({
  content: z.string(),
  contentType: z.optional(z.string()),
  encoding: z._default(Encoding$outboundSchema, "utf-8"),
  model: z.optional(z.string()),
  metadata: z.optional(z.record(z.string(), z.any())),
  idempotencyKey: z.optional(z.string()),
});

export function proveInputToJSON(proveInput: ProveInput): string {
  return JSON.stringify(ProveInput$outboundSchema.parse(proveInput));
}
