/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d90c6c784ca5
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type Security = {
  bearerAuth?: string | undefined;
};

/** @internal */
export type Security$Outbound = {
  BearerAuth?: string | undefined;
};

/** @internal */
export const Security$outboundSchema: z.ZodMiniType<
  Security$Outbound,
  Security
> = z.pipe(
  z.object({
    bearerAuth: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      bearerAuth: "BearerAuth",
    });
  }),
);

export function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
