/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 73652e1a3b81
 */

import * as z from "zod/v4-mini";
import { smartUnion } from "../types/smart-union.js";

export type VerifyRequest2 = {
  proofId?: string | undefined;
  hash: string;
};

export type VerifyRequest1 = {
  proofId: string;
  hash?: string | undefined;
};

export type VerifyRequestUnion = VerifyRequest1 | VerifyRequest2;

/** @internal */
export type VerifyRequest2$Outbound = {
  proofId?: string | undefined;
  hash: string;
};

/** @internal */
export const VerifyRequest2$outboundSchema: z.ZodMiniType<
  VerifyRequest2$Outbound,
  VerifyRequest2
> = z.object({
  proofId: z.optional(z.string()),
  hash: z.string(),
});

export function verifyRequest2ToJSON(verifyRequest2: VerifyRequest2): string {
  return JSON.stringify(VerifyRequest2$outboundSchema.parse(verifyRequest2));
}

/** @internal */
export type VerifyRequest1$Outbound = {
  proofId: string;
  hash?: string | undefined;
};

/** @internal */
export const VerifyRequest1$outboundSchema: z.ZodMiniType<
  VerifyRequest1$Outbound,
  VerifyRequest1
> = z.object({
  proofId: z.string(),
  hash: z.optional(z.string()),
});

export function verifyRequest1ToJSON(verifyRequest1: VerifyRequest1): string {
  return JSON.stringify(VerifyRequest1$outboundSchema.parse(verifyRequest1));
}

/** @internal */
export type VerifyRequestUnion$Outbound =
  | VerifyRequest1$Outbound
  | VerifyRequest2$Outbound;

/** @internal */
export const VerifyRequestUnion$outboundSchema: z.ZodMiniType<
  VerifyRequestUnion$Outbound,
  VerifyRequestUnion
> = smartUnion([
  z.lazy(() => VerifyRequest1$outboundSchema),
  z.lazy(() => VerifyRequest2$outboundSchema),
]);

export function verifyRequestUnionToJSON(
  verifyRequestUnion: VerifyRequestUnion,
): string {
  return JSON.stringify(
    VerifyRequestUnion$outboundSchema.parse(verifyRequestUnion),
  );
}
